apiVersion: v1
kind: Template
labels:
  template: thoth-cleanup-cronjob
  thoth: 0.1.0
metadata:
  name: thoth-cleanup-job
  annotations:
    description: This is Thoth Core - Cleanup Job
    openshift.io/display-name: "Thoth: Cleanup Job"
    version: 0.1.0
    tags: poc,thoth,ai-stacks,graph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Cleanup Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: cleanup-job
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    labels:
      app: thoth-core
  spec:
    schedule: "@weekly"
    suspend: true
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: analyzer
            containers:
            - image: cleanup-cronjob
              name: cleanup-cronjob
              env:
               - name: KUBERNETES_VERIFY_TLS
                 value: "0"
               - name: THOTH_ANALYZER_CLEANUP_TIME
                 valueFrom:
                  configMapKeyRef:
                    key: analyzer-cleanup-time
                    name: thoth
               - name: KUBERNETES_API_URL
                 value: 'https://kubernetes.default.svc.cluster.local'
               - name: THOTH_LOG_CLEANUP_JOB
                 valueFrom:
                  configMapKeyRef:
                    key: log-cleanup-job
                    name: thoth
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "250m"
            restartPolicy: OnFailure

parameters:
- description: Time before analyzer pod gets removed from etcd.
  displayName: Thoth analyzer cleanup time
  required: true
  name: THOTH_ANALYZER_CLEANUP_TIME
  value: '7d'

